export enum Line {
  Elizabeth = "Elizabeth",
  DLR = "DLR",
  Central = "Central",
  Northern = "Northern",
  Piccadilly = "Piccadilly",
  Waterloo = "Waterloo",
  Victoria = "Victoria",
  Bakerloo = "Bakerloo",
  Jubilee = "Jubilee",
  District = "District",
  Circle = "Circle",
  Metropolitan = "Metropolitan",
  Overground = "Overground",
  HammersmithCity = "HammersmithСity",
  Tram = "Tram",
  CloudCableCar = "CloudCableCar",
}

export enum Station {
  Shenfield = "Shenfield",
  Bank = "Bank",
  Leyton = "Leyton",
  Aldgate = "Aldgate",
  Rotherhithe = "Rotherhithe",
  Epping = "Epping",
  Debden = "Debden",
  Loughton = "Loughton",
  LimeHouse = "LimeHouse",
  Westferry = "Westferry",
  Poplar = "Poplar",
  Blackwall = "Blackwall",
  MansionHouse = "MansionHouse",
  CaledonianRoad = "CaledonianRoad",
  Knightsbridge = "Knightsbridge",
  HydeParkCorner = "HydeParkCorner",
  BaronsCourt = "BaronsCourt",
  CoventGarden = "CoventGarden",
  Vauxhall = "Vauxhall",
  Pimlico = "Pimlico",
  EdgwareRoud = "EdgwareRoud",
  Marylebone = "Marylebone",
  Upminster = "Upminster",
  UpminsterBridge = "UpminsterBridge",
  Hornchurch = "Hornchurch",
  ElmPark = "ElmPark",
  DagenhamEast = "DagenhamEast",
  DagenhamHeathway = "DagenhamHeathway",
  Becontree = "Becontree",
  Upney = "Upney",
  Chingford = "Chingford",
  HighamsPark = "HighamsPark",
  WoodStreet = "WoodStreet",
  Bermondsey = "Bermondsey",
  Stanmore = "Stanmore",
  CanonsPark = "CanonsPark",
  Queensbury = "Queensbury",
  Borough = "Borough",
  Edgware = "Edgware",
  BurntOak = "BurntOak",
  Colindale = "Colindale",
  Chesham = "Chesham",
  Amersham = "Amersham",
  ChalfontLatimer = "ChalfontLatimer",
  Chorleywood = "Chorleywood",
  Watford = "Watford",
  Rickmansworth = "Rickmansworth",
  Croxley = "Croxley",
  MoorPark = "MoorPark",
  Northwood = "Northwood",
  NorthwoodHills = "Northwood Hills",
  Pinner = "Pinner",
  NorthHarrow = "NorthHarrow",
  BeckenhamJunction = "BeckenhamJunction",
  BeckenhamRoad = "BeckenhamRoad",
  AvenueRoad = "AvenueRoad",
  Birkbeck = "Birkbeck",
  HarringtonRoad = "HarringtonRoad",
  ElmersEnd = "ElmersEnd",
  Arena = "Arena",
  Woodside = "Woodside",
  BlackhorseLane = "BlackhorseLane",
  Addiscombe = "Addiscombe",
  Sandilands = "Sandilands",
  LloydPark = "LloydPark",
  CoombeLane = "CoombeLane",
  GravelHill = "GravelHill",
  AddingtonVillage = "AddingtonVillage",
  Fieldway = "Fieldway",
  KingHenrysDrive = "KingHenrysDrive",
  NewAddington = "NewAddington",
  LebanonRoad = "LebanonRoad",
  EastCroydon = "EastCroydon",
  WellesleyRoad = "WellesleyRoad",
  Centrale = "Centrale",
  ChurchStreet = "ChurchStreet",
  ReevesCorner = "ReevesCorner",
  GeorgeStreet = "GeorgeStreet",
  WandlePark = "WandlePark",
  WaddonMarsh = "WaddonMarsh",
  AmpereWay = "AmpereWay",
  TherapiaLane = "TherapiaLane",
  BeddingtonLane = "BeddingtonLane",
  MitchamJunction = "MitchamJunction",
  Mitcham = "Mitcham",
  BelgraveWalk = "BelgraveWalk",
  PhippsBridge = "PhippsBridge",
  MordenRoad = "MordenRoad",
  MertonPark = "MertonPark",
  DundonaldRoad = "DundonaldRoad",
  IFSCloudRoyalDocks = "IFSCloudRoyalDocks",
  GantsHill = "GantsHill",
  Redbridge = "Redbridge",
  Leytonstone = "Leytonstone",
  TheydonBois = "TheydonBois",
  KingsCrossStPancras = "KingsCrossStPancras",
  Moorgate = "Moorgate",
  StPauls = "StPauls",
  Holborn = "Holborn",
  EustonSquare = "EustonSquare",
  LancasterGate = "LancasterGate",
  Monument = "Monument",
  Barbican = "Barbican",
  Kilburn = "Kilburn",
  Neasden = "Neasden",
  WillesdenGreen = "WillesdenGreen",
  WestHampstead = "WestHampstead",
  DollisHill = " DollisHill",
  Kingsbury = "Kingsbury",
  HollandPark = "HollandPark",
  PrestonRoad = "PrestonRoad",
  WembleyPark = "WembleyPark",
  BakerStreet = "BakerStreet",
  GreatPortlandStreet = "GreatPortlandStreet",
  Embankment = "Embankment",
  Temple = "Temple",
  StJamessPark = "StJamessPark",
  GloucesterRoad = "GloucesterRoad",
  Westminster = "Westminster",
  SloaneSquare = "SloaneSquare",
  Bayswater = "Bayswater",
  FinchleyRoad = "FinchleyRoad",
  HighStreetKensington = "HighStreetKensington",
  NottingHillGate = "NottingHillGate",
  Blackfriars = "Blackfriars",
  Victoria = "Victoria",
  Paddington = "Paddington",
  CannonStreet = "CannonStreet",
  LiverpoolStreet = "LiverpoolStreet",
  SouthKensington = "SouthKensington",
  SwissCottage = "SwissCottage",
  StJohnsWood = "StJohnsWood",
  CanaryWharf = "CanaryWharf",
  CustomHouseForExCeL = "CustomHouseForExCeL",
  LambethNorth = "LambethNorth",
  PutneyBridge = "PutneyBridge",
  Reading = "Reading",
  Twyford = "Twyford",
  Burnham = "Burnham",
  Maidenhead = "Maidenhead",
  Taplow = "Taplow",
  Slough = "Slough",
  Langley = "Langley",
  Iver = "Iver",
  WestDrayton = "WestDrayton",
  HayesHarlington = "HayesHarlington",
  Southall = "Southall",
  Hanwell = "Hanwell",
  WestEaling = "WestEaling",
  ActonMainLine = "ActonMainLine",
}

export const LinesByStation: Record<Station, Set<Line>> = {
  [Station.Shenfield]: new Set([Line.Elizabeth]),
  [Station.Reading]: new Set([Line.Elizabeth]),
  [Station.Twyford]: new Set([Line.Elizabeth]),
  [Station.Burnham]: new Set([Line.Elizabeth]),
  [Station.Maidenhead]: new Set([Line.Elizabeth]),
  [Station.Taplow]: new Set([Line.Elizabeth]),
  [Station.Slough]: new Set([Line.Elizabeth]),
  [Station.Langley]: new Set([Line.Elizabeth]),
  [Station.Iver]: new Set([Line.Elizabeth]),
  [Station.WestDrayton]: new Set([Line.Elizabeth]),
  [Station.HayesHarlington]: new Set([Line.Elizabeth]),
  [Station.Southall]: new Set([Line.Elizabeth]),
  [Station.Hanwell]: new Set([Line.Elizabeth]),
  [Station.WestEaling]: new Set([Line.Elizabeth]),
  [Station.ActonMainLine]: new Set([Line.Elizabeth]),

  [Station.Rotherhithe]: new Set([Line.Overground]),
  [Station.Chingford]: new Set([Line.Overground]),
  [Station.HighamsPark]: new Set([Line.Overground]),
  [Station.WoodStreet]: new Set([Line.Overground]),

  [Station.Bermondsey]: new Set([Line.Jubilee]),
  [Station.Stanmore]: new Set([Line.Jubilee]),
  [Station.CanonsPark]: new Set([Line.Jubilee]),
  [Station.Queensbury]: new Set([Line.Jubilee]),
  [Station.Kingsbury]: new Set([Line.Jubilee]),
  [Station.Neasden]: new Set([Line.Jubilee]),
  [Station.DollisHill]: new Set([Line.Jubilee]),
  [Station.WillesdenGreen]: new Set([Line.Jubilee]),
  [Station.Kilburn]: new Set([Line.Jubilee]),
  [Station.SwissCottage]: new Set([Line.Jubilee]),
  [Station.StJohnsWood]: new Set([Line.Jubilee]),

  [Station.Borough]: new Set([Line.Northern]),
  [Station.Edgware]: new Set([Line.Northern]),
  [Station.BurntOak]: new Set([Line.Northern]),
  [Station.Colindale]: new Set([Line.Northern]),

  [Station.CaledonianRoad]: new Set([Line.Piccadilly]),
  [Station.Knightsbridge]: new Set([Line.Piccadilly]),
  [Station.HydeParkCorner]: new Set([Line.Piccadilly]),
  [Station.BaronsCourt]: new Set([Line.Piccadilly]),
  [Station.CoventGarden]: new Set([Line.Piccadilly]),

  [Station.Vauxhall]: new Set([Line.Victoria]),
  [Station.Pimlico]: new Set([Line.Victoria]),

  [Station.Marylebone]: new Set([Line.Bakerloo]),
  [Station.EdgwareRoud]: new Set([Line.Bakerloo]),
  [Station.LambethNorth]: new Set([Line.Bakerloo]),

  [Station.Leyton]: new Set([Line.Central]),
  [Station.Epping]: new Set([Line.Central]),
  [Station.Debden]: new Set([Line.Central]),
  [Station.Loughton]: new Set([Line.Central]),
  [Station.GantsHill]: new Set([Line.Central]),
  [Station.Redbridge]: new Set([Line.Central]),
  [Station.Leytonstone]: new Set([Line.Central]),
  [Station.TheydonBois]: new Set([Line.Central]),
  [Station.StPauls]: new Set([Line.Central]),
  [Station.LancasterGate]: new Set([Line.Central]),
  [Station.HollandPark]: new Set([Line.Central]),

  [Station.LimeHouse]: new Set([Line.DLR]),
  [Station.Westferry]: new Set([Line.DLR]),
  [Station.Poplar]: new Set([Line.DLR]),
  [Station.Blackwall]: new Set([Line.DLR]),
  [Station.CustomHouseForExCeL]: new Set([Line.DLR]),

  [Station.Upminster]: new Set([Line.District]),
  [Station.UpminsterBridge]: new Set([Line.District]),
  [Station.Hornchurch]: new Set([Line.District]),
  [Station.ElmPark]: new Set([Line.District]),
  [Station.DagenhamEast]: new Set([Line.District]),
  [Station.DagenhamHeathway]: new Set([Line.District]),
  [Station.Becontree]: new Set([Line.District]),
  [Station.Upney]: new Set([Line.District]),
  [Station.PutneyBridge]: new Set([Line.District]),

  [Station.Chesham]: new Set([Line.Metropolitan]),
  [Station.Amersham]: new Set([Line.Metropolitan]),
  [Station.ChalfontLatimer]: new Set([Line.Metropolitan]),
  [Station.Chorleywood]: new Set([Line.Metropolitan]),
  [Station.Watford]: new Set([Line.Metropolitan]),
  [Station.Rickmansworth]: new Set([Line.Metropolitan]),
  [Station.Croxley]: new Set([Line.Metropolitan]),
  [Station.MoorPark]: new Set([Line.Metropolitan]),
  [Station.Northwood]: new Set([Line.Metropolitan]),
  [Station.NorthwoodHills]: new Set([Line.Metropolitan]),
  [Station.Pinner]: new Set([Line.Metropolitan]),
  [Station.NorthHarrow]: new Set([Line.Metropolitan]),
  [Station.PrestonRoad]: new Set([Line.Metropolitan]),

  [Station.BeckenhamJunction]: new Set([Line.Tram]),
  [Station.BeckenhamRoad]: new Set([Line.Tram]),
  [Station.AvenueRoad]: new Set([Line.Tram]),
  [Station.Birkbeck]: new Set([Line.Tram]),
  [Station.HarringtonRoad]: new Set([Line.Tram]),
  [Station.ElmersEnd]: new Set([Line.Tram]),
  [Station.Arena]: new Set([Line.Tram]),
  [Station.Woodside]: new Set([Line.Tram]),
  [Station.BlackhorseLane]: new Set([Line.Tram]),
  [Station.Addiscombe]: new Set([Line.Tram]),
  [Station.Sandilands]: new Set([Line.Tram]),
  [Station.LloydPark]: new Set([Line.Tram]),
  [Station.CoombeLane]: new Set([Line.Tram]),
  [Station.GravelHill]: new Set([Line.Tram]),
  [Station.AddingtonVillage]: new Set([Line.Tram]),
  [Station.Fieldway]: new Set([Line.Tram]),
  [Station.KingHenrysDrive]: new Set([Line.Tram]),
  [Station.NewAddington]: new Set([Line.Tram]),
  [Station.LebanonRoad]: new Set([Line.Tram]),
  [Station.EastCroydon]: new Set([Line.Tram]),
  [Station.GeorgeStreet]: new Set([Line.Tram]),
  [Station.WellesleyRoad]: new Set([Line.Tram]),
  [Station.Centrale]: new Set([Line.Tram]),
  [Station.ChurchStreet]: new Set([Line.Tram]),
  [Station.ReevesCorner]: new Set([Line.Tram]),
  [Station.WandlePark]: new Set([Line.Tram]),
  [Station.WaddonMarsh]: new Set([Line.Tram]),
  [Station.AmpereWay]: new Set([Line.Tram]),
  [Station.TherapiaLane]: new Set([Line.Tram]),
  [Station.BeddingtonLane]: new Set([Line.Tram]),
  [Station.Mitcham]: new Set([Line.Tram]),
  [Station.MitchamJunction]: new Set([Line.Tram]),
  [Station.BelgraveWalk]: new Set([Line.Tram]),
  [Station.PhippsBridge]: new Set([Line.Tram]),
  [Station.MordenRoad]: new Set([Line.Tram]),
  [Station.MertonPark]: new Set([Line.Tram]),
  [Station.DundonaldRoad]: new Set([Line.Tram]),

  [Station.IFSCloudRoyalDocks]: new Set([Line.CloudCableCar]),

  [Station.Bank]: new Set([Line.DLR, Line.Central, Line.Northern]),
  [Station.WembleyPark]: new Set([Line.Jubilee, Line.Metropolitan]),
  [Station.Monument]: new Set([Line.Circle, Line.District]),
  [Station.CannonStreet]: new Set([Line.Circle, Line.District]),
  [Station.MansionHouse]: new Set([Line.Circle, Line.District]),
  [Station.Blackfriars]: new Set([Line.Circle, Line.District]),
  [Station.Temple]: new Set([Line.Circle, Line.District]),
  [Station.StJamessPark]: new Set([Line.Circle, Line.District]),
  [Station.SloaneSquare]: new Set([Line.Circle, Line.District]),
  [Station.Bayswater]: new Set([Line.Circle, Line.District]),
  [Station.HighStreetKensington]: new Set([Line.Circle, Line.District]),
  [Station.NottingHillGate]: new Set([
    Line.Circle,
    Line.District,
    Line.Central,
  ]),
  [Station.Aldgate]: new Set([Line.Circle, Line.Metropolitan]),
  [Station.Holborn]: new Set([Line.Central, Line.Piccadilly]),
  [Station.KingsCrossStPancras]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
    Line.Northern,
    Line.Piccadilly,
    Line.Victoria,
  ]),
  [Station.Paddington]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.District,
    Line.Elizabeth,
    Line.HammersmithCity,
  ]),
  [Station.BakerStreet]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.HammersmithCity,
    Line.Jubilee,
    Line.Metropolitan,
  ]),
  [Station.Embankment]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.District,
    Line.Northern,
  ]),
  [Station.Westminster]: new Set([Line.Circle, Line.District, Line.Jubilee]),
  [Station.SouthKensington]: new Set([
    Line.Circle,
    Line.District,
    Line.Piccadilly,
  ]),
  [Station.GloucesterRoad]: new Set([
    Line.Circle,
    Line.District,
    Line.Piccadilly,
  ]),
  [Station.Moorgate]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
    Line.Northern,
  ]),
  [Station.EustonSquare]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.Barbican]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.GreatPortlandStreet]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.Victoria]: new Set([Line.Circle, Line.District, Line.Victoria]),
  [Station.LiverpoolStreet]: new Set([
    Line.Elizabeth,
    Line.Circle,
    Line.Central,
    Line.HammersmithCity,
    Line.Overground,
    Line.Metropolitan,
  ]),
  [Station.CanaryWharf]: new Set([Line.Elizabeth, Line.DLR, Line.Jubilee]),
  [Station.WestHampstead]: new Set([Line.Overground, Line.Jubilee]),
  [Station.FinchleyRoad]: new Set([Line.Jubilee, Line.Metropolitan]),
};

// spread values for enum for single word stations
// needed for the search functionality later
export const multiWordStationNames: Partial<Record<Station, string>> = {
  [Station.StPauls]: "St Paul’s",
  [Station.KingsCrossStPancras]: "King’s Cross & St Pancras International",
  [Station.MansionHouse]: "Mansion House",
  [Station.CanonsPark]: "Canons Park",
  [Station.WillesdenGreen]: "Willesden Green",
  [Station.DollisHill]: "Dollis Hill",
  [Station.PrestonRoad]: "Preston Road",
  [Station.WembleyPark]: "Wembley Park",
  [Station.BakerStreet]: "Baker Street",
  [Station.GreatPortlandStreet]: "Great Portland Street",
  [Station.StJamessPark]: "St James's Park",
  [Station.GloucesterRoad]: "Gloucester Road",
  [Station.SloaneSquare]: "Sloane Square",
  [Station.HighStreetKensington]: "High Street Kensington",
  [Station.NottingHillGate]: "Notting Hill Gate",
  [Station.CannonStreet]: "Cannon Street",
  [Station.LiverpoolStreet]: "Liverpool Street",
  [Station.SouthKensington]: "South Kensington",
  [Station.CanaryWharf]: "Canary Wharf",
  [Station.PutneyBridge]: "Putney Bridge",
  [Station.HayesHarlington]: "Hayes & Harlington",
  [Station.WestEaling]: "West Ealing",
  [Station.ActonMainLine]: "Acton Main Line",
  [Station.CustomHouseForExCeL]: "Custom House for ExCeL",
  [Station.LambethNorth]: "Lambeth North",
  [Station.LancasterGate]: "Lancaster Gate",
  [Station.StJohnsWood]: "St John’s Wood",
  [Station.WestHampstead]: "West Hampstead",
  [Station.FinchleyRoad]: "Finchley Road",
  [Station.SwissCottage]: "Swiss Cottage",
  [Station.BeckenhamJunction]: "Beckenham Junction",
  [Station.LebanonRoad]: "Lebanon Road",
  [Station.EastCroydon]: "East Croydon",
  [Station.MitchamJunction]: "Mitcham Junction",
  [Station.GeorgeStreet]: "George Street",
  [Station.WaddonMarsh]: "Waddon Marsh",
  [Station.TherapiaLane]: "Therapia Lane",
  [Station.MordenRoad]: "Morden Road",
  [Station.BelgraveWalk]: "Belgrave Walk",
  [Station.PhippsBridge]: "Phipps Bridge",
  [Station.ChurchStreet]: "Church Street",
  [Station.PhippsBridge]: "Wandle Park",
  [Station.AmpereWay]: "Ampere Way",
  [Station.BeddingtonLane]: "Beddington Lane",
  [Station.ReevesCorner]: "Reeves Corner",
  [Station.WellesleyRoad]: "Wellesley Road",
  [Station.LloydPark]: "Lloyd Park",
  [Station.CoombeLane]: "Coombe Lane",
  [Station.GravelHill]: "Gravel Hill",
  [Station.AddingtonVillage]: "Addington Village",
  [Station.NewAddington]: "New Addington",
  [Station.KingHenrysDrive]: "King Henry’s Drive",
  [Station.MertonPark]: "Merton Park",
  [Station.BlackhorseLane]: "Blackhorse Lane",
  [Station.DundonaldRoad]: "Dundonald Road",
  [Station.HarringtonRoad]: "Harrington Road",
  [Station.CaledonianRoad]: "Caledonian Road",
  [Station.StPauls]: "St Paul's",
};
