export enum Line {
  Elizabeth = "Elizabeth",
  DLR = "DLR",
  Central = "Central",
  Northern = "Northern",
  Piccadilly = "Piccadilly",
  Waterloo = "Waterloo",
  Victoria = "Victoria",
  Bakerloo = "Bakerloo",
  Jubilee = "Jubilee",
  District = "District",
  Circle = "Circle",
  Metropolitan = "Metropolitan",
  Overground = "Overground",
  HammersmithCity = "HammersmithCity",
  Tram = "Tram",
  CloudCableCar = "CloudCableCar",
}

export enum Station {
  Shenfield = "Shenfield",
  Bank = "Bank",
  Leyton = "Leyton",
  Aldgate = "Aldgate",
  Rotherhithe = "Rotherhithe",
  Epping = "Epping",
  Debden = "Debden",
  Loughton = "Loughton",
  TowerGateway = "TowerGateway",
  Shadwell = "Shadwell",
  ShadwellDLR = "ShadwellDLR",
  Limehouse = "Limehouse",
  Westferry = "Westferry",
  Poplar = "Poplar",
  Blackwall = "Blackwall",
  EastIndia = "EastIndia",
  StarLane = "StarLane",
  AbbeyRoad = "AbbeyRoad",
  StratfordHighStreet = "StratfordHighStreet",
  StratfordInternational = "StratfordInternational",
  PuddingMillLane = "PuddingMillLane",
  AllSaints = "AllSaints",
  LangdonPark = "LangdonPark",
  DevonsRoad = "DevonsRoad",
  ElversonRoad = "ElversonRoad",
  IslandGardens = "IslandGardens",
  CanningTown = "CanningTown",
  WestIndiaQuay = "WestIndiaQuay",
  HeronQuays = "HeronQuays",
  BowChurch = "BowChurch",
  RoyalVictoria = "RoyalVictoria",
  Mudchute = "Mudchute",
  Crossharbour = "Crossharbour",
  SouthQuay = "SouthQuay",
  DeptfordBridge = "DeptfordBridge",
  CuttySarkForMaritimeGreenwich = "CuttySarkForMaritimeGreenwich",
  Greenwich = "Greenwich",
  Lewisham = "Lewisham",
  Woolwich = "Woolwich",
  WoolwichArsenal = "WoolwichArsenal",
  LondonCityAirport = "LondonCityAirport",
  Beckton = "Beckton",
  GallionsReach = "GallionsReach",
  Cyprus = "Cyprus",
  BecktonPark = "BecktonPark",
  RoyalAlbert = "RoyalAlbert",
  PrinceRegent = "PrinceRegent",
  KingGeorgeV = "KingGeorgeV",
  PontoonDock = "PontoonDock",
  WestSilvertown = "WestSilvertown",
  MansionHouse = "MansionHouse",
  CaledonianRoad = "CaledonianRoad",
  Knightsbridge = "Knightsbridge",
  HydeParkCorner = "HydeParkCorner",
  BaronsCourt = "BaronsCourt",
  CoventGarden = "CoventGarden",
  Vauxhall = "Vauxhall",
  Pimlico = "Pimlico",
  Marylebone = "Marylebone",
  Upminster = "Upminster",
  UpminsterBridge = "UpminsterBridge",
  Hornchurch = "Hornchurch",
  ElmPark = "ElmPark",
  DagenhamEast = "DagenhamEast",
  DagenhamHeathway = "DagenhamHeathway",
  Becontree = "Becontree",
  Upney = "Upney",
  Chingford = "Chingford",
  HighamsPark = "HighamsPark",
  WoodStreet = "WoodStreet",
  Bermondsey = "Bermondsey",
  Stanmore = "Stanmore",
  CanonsPark = "CanonsPark",
  Queensbury = "Queensbury",
  Borough = "Borough",
  Edgware = "Edgware",
  BurntOak = "BurntOak",
  Colindale = "Colindale",
  Chesham = "Chesham",
  Amersham = "Amersham",
  ChalfontLatimer = "ChalfontLatimer",
  Chorleywood = "Chorleywood",
  Watford = "Watford",
  Rickmansworth = "Rickmansworth",
  Croxley = "Croxley",
  MoorPark = "MoorPark",
  Northwood = "Northwood",
  NorthwoodHills = "Northwood Hills",
  Pinner = "Pinner",
  NorthHarrow = "NorthHarrow",
  BeckenhamJunction = "BeckenhamJunction",
  BeckenhamRoad = "BeckenhamRoad",
  AvenueRoad = "AvenueRoad",
  Birkbeck = "Birkbeck",
  HarringtonRoad = "HarringtonRoad",
  ElmersEnd = "ElmersEnd",
  Arena = "Arena",
  Woodside = "Woodside",
  BlackhorseLane = "BlackhorseLane",
  Addiscombe = "Addiscombe",
  Sandilands = "Sandilands",
  LloydPark = "LloydPark",
  CoombeLane = "CoombeLane",
  GravelHill = "GravelHill",
  AddingtonVillage = "AddingtonVillage",
  Fieldway = "Fieldway",
  KingHenrysDrive = "KingHenrysDrive",
  NewAddington = "NewAddington",
  LebanonRoad = "LebanonRoad",
  EastCroydon = "EastCroydon",
  WellesleyRoad = "WellesleyRoad",
  Centrale = "Centrale",
  ChurchStreet = "ChurchStreet",
  ReevesCorner = "ReevesCorner",
  GeorgeStreet = "GeorgeStreet",
  WandlePark = "WandlePark",
  WaddonMarsh = "WaddonMarsh",
  AmpereWay = "AmpereWay",
  TherapiaLane = "TherapiaLane",
  BeddingtonLane = "BeddingtonLane",
  MitchamJunction = "MitchamJunction",
  Mitcham = "Mitcham",
  BelgraveWalk = "BelgraveWalk",
  PhippsBridge = "PhippsBridge",
  MordenRoad = "MordenRoad",
  MertonPark = "MertonPark",
  DundonaldRoad = "DundonaldRoad",
  IFSCloudRoyalDocks = "IFSCloudRoyalDocks",
  GantsHill = "GantsHill",
  Redbridge = "Redbridge",
  Leytonstone = "Leytonstone",
  TheydonBois = "TheydonBois",
  KingsCrossStPancras = "KingsCrossStPancras",
  Moorgate = "Moorgate",
  StPauls = "StPauls",
  Holborn = "Holborn",
  EustonSquare = "EustonSquare",
  LancasterGate = "LancasterGate",
  TowerHill = "TowerHill",
  Monument = "Monument",
  Barbican = "Barbican",
  Kilburn = "Kilburn",
  Neasden = "Neasden",
  WillesdenGreen = "WillesdenGreen",
  WestHampstead = "WestHampstead",
  WestHampsteadJubilee = "WestHampsteadJubilee",
  DollisHill = " DollisHill",
  Kingsbury = "Kingsbury",
  HollandPark = "HollandPark",
  PrestonRoad = "PrestonRoad",
  WembleyPark = "WembleyPark",
  BakerStreet = "BakerStreet",
  GreatPortlandStreet = "GreatPortlandStreet",
  Embankment = "Embankment",
  Temple = "Temple",
  StJamessPark = "StJamessPark",
  GloucesterRoad = "GloucesterRoad",
  Westminster = "Westminster",
  SloaneSquare = "SloaneSquare",
  Bayswater = "Bayswater",
  FinchleyRoad = "FinchleyRoad",
  HighStreetKensington = "HighStreetKensington",
  NottingHillGate = "NottingHillGate",
  Blackfriars = "Blackfriars",
  Victoria = "Victoria",
  Paddington = "Paddington",
  CannonStreet = "CannonStreet",
  LiverpoolStreet = "LiverpoolStreet",
  SouthKensington = "SouthKensington",
  SwissCottage = "SwissCottage",
  StJohnsWood = "StJohnsWood",
  CanaryWharf = "CanaryWharf",
  CustomHouseForExCeL = "CustomHouseForExCeL",
  LambethNorth = "LambethNorth",
  PutneyBridge = "PutneyBridge",
  Reading = "Reading",
  Twyford = "Twyford",
  Burnham = "Burnham",
  Maidenhead = "Maidenhead",
  Taplow = "Taplow",
  Slough = "Slough",
  Langley = "Langley",
  Iver = "Iver",
  WestDrayton = "WestDrayton",
  HayesHarlington = "HayesHarlington",
  Southall = "Southall",
  Hanwell = "Hanwell",
  WestEaling = "WestEaling",
  ActonMainLine = "ActonMainLine",
  ClaphamJunction = "ClaphamJunction",
  Hoxton = "Hoxton",
  Haggerston = "Haggerston",
  DalstonJunction = "DalstonJunction",
  ShoreditchHighStreet = "ShoreditchHighStreet",
  CrouchHill = "CrouchHill",
  UpperHolloway = "UpperHolloway",
  SouthTottenham = "SouthTottenham",
  HarringayGreenLanes = "HarringayGreenLanes",
  ActonTown = "ActonTown",
  WoodgrangePark = "WoodgrangePark",
  WalthamstowQueensRoad = "WalthamstowQueensRoad",
  LeytonMidlandRoad = "LeytonMidlandRoad",
  LeytonstoneHighRoad = "LeytonstoneHighRoad",
  WansteadPark = "WansteadPark",
  ImperialWharf = "ImperialWharf",
  WandsworthRoad = "WandsworthRoad",
  DenmarkHill = "DenmarkHill",
  PeckhamRye = "PeckhamRye",
  QueensRoadPeckham = "QueensRoadPeckham",
  SurreyQuays = "SurreyQuays",
  CrystalPalace = "CrystalPalace",
  NewCross = "NewCross",
  Sydenham = "Sydenham",
  NewCrossGate = "NewCrossGate",
  Wapping = "Wapping",
  WestCroydon = "WestCroydon",
  WestCroydonTram = "WestCroydonTram",
  Brockley = "Brockley",
  HonorOakPark = "HonorOakPark",
  PengeWest = "PengeWest",
  Anerley = "Anerley",
  ForestHill = "ForestHill",
  NorwoodJunction = "NorwoodJunction",
  Canonbury = "Canonbury",
  Homerton = "Homerton",
  HackneyWick = "HackneyWick",
  CaledonianRoadBarnsbury = "CaledonianRoadBarnsbury",
  HackneyCentral = "HackneyCentral",
  DalstonKingsland = "DalstonKingsland",
  CamdenRoad = "CamdenRoad",
  KentishTownWest = "KentishTownWest",
  GospelOak = "GospelOak",
  Brondesbury = "Brondesbury",
  FinchleyRoadFrognal = "FinchleyRoadFrognal",
  HampsteadHeath = "HampsteadHeath",
  BrondesburyPark = "BrondesburyPark",
  KensalRise = "KensalRise",
  SouthHampstead = "SouthHampstead",
  KilburnHighRoad = "KilburnHighRoad",
  KensingtonOlympia = "KensingtonOlympia",
  SouthActon = "SouthActon",
  ActonCentral = "ActonCentral",
  AbbeyWood = "AbbeyWood",
  Brixton = "Brixton",
  Stockwell = "Stockwell",
  WalthamstowCentral = "WalthamstowCentral",
  TottenhamHale = "TottenhamHale",
  SevenSisters = "SevenSisters",
  FinsburyPark = "FinsburyPark",
  HighburyIslington = "HighburyIslington",
  BlackhorseRoad = "BlackhorseRoad",
  HollowayRoad = "Road",
  Arsenal = "Arsenal",
  ManorHouse = "ManorHouse",
  TurnpikeLane = "TurnpikeLane",
  WoodGreen = "WoodGreen",
  BoundsGreen = "BoundsGreen",
  ArnosGrove = "ArnosGrove",
  Southgate = "Southgate",
  Cockfosters = "Cockfosters",
  Oakwood = "Oakwood",
  RussellSquare = "RussellSquare",
  HeathrowTerminals23 = "HeathrowTerminals23",
  HeathrowTerminal5 = "HeathrowTerminal5",
  HeathrowTerminal4 = "HeathrowTerminal4",
  HattonCross = "HattonCross",
  HounslowWest = "HounslowWest",
  HounslowEast = "HounslowEast",
  HounslowCentral = "HounslowCentral",
  Osterley = "Osterley",
  SouthEaling = "SouthEaling",
  BostonManor = "BostonManor",
  Northfields = "Northfields",
  NorthEaling = "NorthEaling",
  ParkRoyal = "ParkRoyal",
  Alperton = "Alperton",
  SudburyTown = "SudburyTown",
  SudburyHill = "SudburyHill",
  SouthHarrow = "SouthHarrow",
  RaynersLane = "RaynersLane",
  Balham = "Balham",
  Morden = "Morden",
  SouthWimbledon = "SouthWimbledon",
  ColliersWood = "ColliersWood",
  TootingBroadway = "TootingBroadway",
  TootingBec = "TootingBec",
  ClaphamSouth = "ClaphamSouth",
  ClaphamCommon = "ClaphamCommon",
  Oval = "Oval",
  ClaphamHighStreet = "ClaphamHighStreet",
  ClaphamNorth = "ClaphamNorth",
  Kennington = "Kennington",
  OldStreet = "OldStreet",
  BatterseaPowerStation = "BatterseaPowerStation",
  NineElms = "NineElms",
  Angel = "Angel",
  LeicesterSquare = "LeicesterSquare",
  WarrenStreet = "WarrenStreet",
  GoodgeStreet = "GoodgeStreet",
  MorningtonCrescent = "MorningtonCrescent",
  CamdenTown = "CamdenTown",
  ChalkFarm = "ChalkFarm",
  BelsizePark = "BelsizePark",
  Hampstead = "Hampstead",
  GoldersGreen = "GoldersGreen",
  BrentCross = "BrentCross",
  HendonCentral = "HendonCentral",
  TufnellPark = "TufnellPark",
  KentishTown = "KentishTown",
  Archway = "Archway",
  Highgate = "Highgate",
  EastFinchley = "EastFinchley",
  FinchleyCentral = "FinchleyCentral",
  WestFinchley = "WestFinchley",
  WoodsidePark = "WoodsidePark",
  TotteridgeWhetstone = "TotteridgeWhetstone",
  HighBarnet = "HighBarnet",
  MillHillEast = "MillHillEast",
  NorthGreenwich = "NorthGreenwich",
  Waterloo = "Waterloo",
  Southwark = "Southwark",
  LondonBridge = "LondonBridge",
  GreenPark = "GreenPark",
  CanadaWater = "CanadaWater",
  IFSCloudGreenwichPeninsula = "IFSCloudGreenwichPeninsula",
  Richmond = "Richmond",
  KewGardens = "KewGardens",
  Gunnersbury = "Gunnersbury",
  EalingCommon = "EalingCommon",
  WestKensington = "WestKensington",
  RavenscourtPark = "RavenscourtPark",
  StamfordBrook = "StamfordBrook",
  TurnhamGreen = "TurnhamGreen",
  ChiswickPark = "ChiswickPark",
  EarlsCourt = "EarlsCourt",
  Wimbledon = "Wimbledon",
  WestBrompton = "WestBrompton",
  WimbledonPark = "WimbledonPark",
  Southfields = "Southfields",
  EastPutney = "EastPutney",
  ParsonsGreen = "ParsonsGreen",
  FulhamBroadway = "FulhamBroadway",
  BarkingRiverside = "BarkingRiverside",
  Barking = "Barking",
  UptonPark = "UptonPark",
  Plaistow = "Plaistow",
  EastHam = "EastHam",
  BromleyByBow = "BromleyByBow",
  StepneyGreen = "StepneyGreen",
  AldgateEast = "AldgateEast",
  Whitechapel = "Whitechapel",
  WestHam = "WestHam",
  BowRoad = "BowRoad",
  Hammersmith = "Hammersmith",
  WestbournePark = "WestbournePark",
  RoyalOak = "RoyalOak",
  LadbrokeGrove = "LadbrokeGrove",
  LatimerRoad = "LatimerRoad",
  GoldhawkRoad = "GoldhawkRoad",
  ShepherdsBushMarket = "ShepherdsBushMarket",
  BuckhurstHill = "BuckhurstHill",
  WoodLane = "WoodLane",
  Chigwell = "Chigwell",
  GrangeHill = "GrangeHill",
  RodingValley = "RodingValley",
  NewburyPark = "NewburyPark",
  Barkingside = "Barkingside",
  Fairlop = "Fairlop",
  Hainault = "Hainault",
  Snaresbrook = "Snaresbrook",
  SouthWoodford = "SouthWoodford",
  Woodford = "Woodford",
  Stratford = "Stratford",
  Wanstead = "Wanstead",
  ChanceryLane = "ChanceryLane",
  MileEnd = "MileEnd",
  BethnalGreenCentral = "BethnalGreenCentral",
  BethnalGreenOverground = "BethnalGreenOverground",
  TottenhamCourtRoad = "TottenhamCourtRoad",
  ShepherdsBush = "ShepherdsBush",
  ShepherdsBushOverground = "ShepherdsBushOverground",
  WhiteCity = "WhiteCity",
  EastCity = "EastCity",
  MarbleArch = "MarbleArch",
  Queensway = "Queensway",
  NorthActon = "NorthActon",
  BondStreet = "BondStreet",
  WestActon = "WestActon",
  EalingBroadway = "EalingBroadway",
  WestRuislip = "WestRuislip",
  Northolt = "Northolt",
  Greenford = "Greenford",
  SouthRuislip = "SouthRuislip",
  RuislipGardens = "RuislipGardens",
  HangerLane = "HangerLane",
  Perivale = "Perivale",
  Euston = "Euston",
  CharingCross = "CharingCross",
  PiccadillyCircus = "PiccadillyCircus",
  OxfordCircus = "OxfordCircus",
  RegentsPark = "RegentsPark",
  ElephantCastle = "ElephantCastle",
  EdgwareRoadBakerloo = "EdgwareRoadBakerloo",
  EdgwareRoad = "EdgwareRoad",
  MaidaVale = "MaidaVale",
  WarwickAvenue = "WarwickAvenue",
  KilburnPark = "KilburnPark",
  WembleyCentral = "WembleyCentral",
  WillesdenJunction = "WillesdenJunction",
  Harlesden = "Harlesden",
  StonebridgePark = "StonebridgePark",
  QueensPark = "QueensPark",
  KensalGreen = "KensalGreen",
  SouthKenton = "SouthKenton",
  NorthWembley = "NorthWembley",
  WatfordJunction = "WatfordJunction",
  Bushey = "Bushey",
  HeadstoneLane = "HeadstoneLane",
  Kenton = "Kenton",
  HatchEnd = "HatchEnd",
  CarpendersPark = "CarpendersPark",
  WatfordHighStreet = "WatfordHighStreet",
  HarrowWealdstone = "HarrowWealdstone",
  Farringdon = "Farringdon",
  HarrowOnTheHill = "HarrowOnTheHill",
  Eastcote = "Eastcote",
  RuislipManor = "RuislipManor",
  Ruislip = "Ruislip",
  Hillingdon = "Hillingdon",
  Uxbridge = "Uxbridge",
  Ickenham = "Ickenham",
  WestHarrow = "WestHarrow",
  NorthwickPark = "NorthwickPark",
  ForestGate = "ForestGate",
  ManorPark = "ManorPark",
  Maryland = "Maryland",
  EmersonPark = "EmersonPark",
  SevenKings = "SevenKings",
  Brentwood = "Brentwood",
  HaroldWood = "HaroldWood",
  GideaPark = "GideaPark",
  Romford = "Romford",
  ChadwellHeath = "ChadwellHeath",
  Goodmayes = "Goodmayes",
  Ilford = "Ilford",
  Cheshunt = "Cheshunt",
  EdmontonGreen = "EdmontonGreen",
  HackneyDowns = "HackneyDowns",
  StokeNewington = "StokeNewington",
  StJamesStreet = "StJamesStreet",
  Clapton = "Clapton",
  BushHillPark = "BushHillPark",
  StamfordHill = "StamfordHill",
  EnfieldTown = "EnfieldTown",
  TheobaldsGrove = "TheobaldsGrove",
  TurkeyStreet = "TurkeyStreet",
  Southbury = "Southbury",
  SilverStreet = "SilverStreet",
  WhiteHartLane = "WhiteHartLane",
  BruceGrove = "BruceGrove",
  RectoryRoad = "RectoryRoad",
  LondonFields = "LondonFields",
  CambridgeHeath = "CambridgeHeath",
}

export const LinesByStation: Record<Station, Set<Line>> = {
  [Station.Shenfield]: new Set([Line.Elizabeth]),
  [Station.Reading]: new Set([Line.Elizabeth]),
  [Station.Twyford]: new Set([Line.Elizabeth]),
  [Station.Burnham]: new Set([Line.Elizabeth]),
  [Station.Maidenhead]: new Set([Line.Elizabeth]),
  [Station.Taplow]: new Set([Line.Elizabeth]),
  [Station.Slough]: new Set([Line.Elizabeth]),
  [Station.Langley]: new Set([Line.Elizabeth]),
  [Station.Iver]: new Set([Line.Elizabeth]),
  [Station.WestDrayton]: new Set([Line.Elizabeth]),
  [Station.HayesHarlington]: new Set([Line.Elizabeth]),
  [Station.Southall]: new Set([Line.Elizabeth]),
  [Station.Hanwell]: new Set([Line.Elizabeth]),
  [Station.WestEaling]: new Set([Line.Elizabeth]),
  [Station.ActonMainLine]: new Set([Line.Elizabeth]),
  [Station.Woolwich]: new Set([Line.Elizabeth]),
  [Station.AbbeyWood]: new Set([Line.Elizabeth]),
  [Station.ForestGate]: new Set([Line.Elizabeth]),
  [Station.ManorPark]: new Set([Line.Elizabeth]),
  [Station.Maryland]: new Set([Line.Elizabeth]),
  [Station.SevenKings]: new Set([Line.Elizabeth]),
  [Station.Brentwood]: new Set([Line.Elizabeth]),
  [Station.HaroldWood]: new Set([Line.Elizabeth]),
  [Station.GideaPark]: new Set([Line.Elizabeth]),
  [Station.ChadwellHeath]: new Set([Line.Elizabeth]),
  [Station.Goodmayes]: new Set([Line.Elizabeth]),
  [Station.Ilford]: new Set([Line.Elizabeth]),
  [Station.WestEaling]: new Set([Line.Elizabeth]),
  [Station.ActonMainLine]: new Set([Line.Elizabeth]),
  [Station.Woolwich]: new Set([Line.Elizabeth]),
  [Station.AbbeyWood]: new Set([Line.Elizabeth]),

  [Station.BethnalGreenOverground]: new Set([Line.Overground]),
  [Station.TheobaldsGrove]: new Set([Line.Overground]),
  [Station.BushHillPark]: new Set([Line.Overground]),
  [Station.EnfieldTown]: new Set([Line.Overground]),
  [Station.StamfordHill]: new Set([Line.Overground]),
  [Station.WhiteHartLane]: new Set([Line.Overground]),
  [Station.TurkeyStreet]: new Set([Line.Overground]),
  [Station.Southbury]: new Set([Line.Overground]),
  [Station.SilverStreet]: new Set([Line.Overground]),
  [Station.WhiteHartLane]: new Set([Line.Overground]),
  [Station.LondonFields]: new Set([Line.Overground]),
  [Station.CambridgeHeath]: new Set([Line.Overground]),
  [Station.RectoryRoad]: new Set([Line.Overground]),
  [Station.BruceGrove]: new Set([Line.Overground]),
  [Station.StokeNewington]: new Set([Line.Overground]),
  [Station.HackneyDowns]: new Set([Line.Overground]),
  [Station.StJamesStreet]: new Set([Line.Overground]),
  [Station.Clapton]: new Set([Line.Overground]),
  [Station.Cheshunt]: new Set([Line.Overground]),
  [Station.EdmontonGreen]: new Set([Line.Overground]),
  [Station.EmersonPark]: new Set([Line.Overground]),
  [Station.Rotherhithe]: new Set([Line.Overground]),
  [Station.Chingford]: new Set([Line.Overground]),
  [Station.HighamsPark]: new Set([Line.Overground]),
  [Station.WoodStreet]: new Set([Line.Overground]),
  [Station.ClaphamJunction]: new Set([Line.Overground]),
  [Station.Hoxton]: new Set([Line.Overground]),
  [Station.Haggerston]: new Set([Line.Overground]),
  [Station.DalstonJunction]: new Set([Line.Overground]),
  [Station.ShoreditchHighStreet]: new Set([Line.Overground]),
  [Station.CrouchHill]: new Set([Line.Overground]),
  [Station.UpperHolloway]: new Set([Line.Overground]),
  [Station.SouthTottenham]: new Set([Line.Overground]),
  [Station.HarringayGreenLanes]: new Set([Line.Overground]),
  [Station.WoodgrangePark]: new Set([Line.Overground]),
  [Station.WalthamstowQueensRoad]: new Set([Line.Overground]),
  [Station.LeytonMidlandRoad]: new Set([Line.Overground]),
  [Station.LeytonstoneHighRoad]: new Set([Line.Overground]),
  [Station.WansteadPark]: new Set([Line.Overground]),
  [Station.ImperialWharf]: new Set([Line.Overground]),
  [Station.WandsworthRoad]: new Set([Line.Overground]),
  [Station.DenmarkHill]: new Set([Line.Overground]),
  [Station.PeckhamRye]: new Set([Line.Overground]),
  [Station.QueensRoadPeckham]: new Set([Line.Overground]),
  [Station.SurreyQuays]: new Set([Line.Overground]),
  [Station.CrystalPalace]: new Set([Line.Overground]),
  [Station.NewCross]: new Set([Line.Overground]),
  [Station.Sydenham]: new Set([Line.Overground]),
  [Station.NewCrossGate]: new Set([Line.Overground]),
  [Station.Wapping]: new Set([Line.Overground]),
  [Station.Brockley]: new Set([Line.Overground]),
  [Station.HonorOakPark]: new Set([Line.Overground]),
  [Station.PengeWest]: new Set([Line.Overground]),
  [Station.Anerley]: new Set([Line.Overground]),
  [Station.ForestHill]: new Set([Line.Overground]),
  [Station.NorwoodJunction]: new Set([Line.Overground]),
  [Station.Canonbury]: new Set([Line.Overground]),
  [Station.Homerton]: new Set([Line.Overground]),
  [Station.HackneyWick]: new Set([Line.Overground]),
  [Station.CaledonianRoadBarnsbury]: new Set([Line.Overground]),
  [Station.HackneyCentral]: new Set([Line.Overground]),
  [Station.DalstonKingsland]: new Set([Line.Overground]),
  [Station.CamdenRoad]: new Set([Line.Overground]),
  [Station.KentishTownWest]: new Set([Line.Overground]),
  [Station.GospelOak]: new Set([Line.Overground]),
  [Station.Brondesbury]: new Set([Line.Overground]),
  [Station.FinchleyRoadFrognal]: new Set([Line.Overground]),
  [Station.HampsteadHeath]: new Set([Line.Overground]),
  [Station.BrondesburyPark]: new Set([Line.Overground]),
  [Station.KensalRise]: new Set([Line.Overground]),
  [Station.SouthHampstead]: new Set([Line.Overground]),
  [Station.KilburnHighRoad]: new Set([Line.Overground]),
  [Station.SouthActon]: new Set([Line.Overground]),
  [Station.ActonCentral]: new Set([Line.Overground]),
  [Station.ClaphamHighStreet]: new Set([Line.Overground]),
  [Station.BarkingRiverside]: new Set([Line.Overground]),
  [Station.WatfordJunction]: new Set([Line.Overground]),
  [Station.Bushey]: new Set([Line.Overground]),
  [Station.HeadstoneLane]: new Set([Line.Overground]),
  [Station.HatchEnd]: new Set([Line.Overground]),
  [Station.CarpendersPark]: new Set([Line.Overground]),
  [Station.WatfordHighStreet]: new Set([Line.Overground]),

  [Station.Bermondsey]: new Set([Line.Jubilee]),
  [Station.Stanmore]: new Set([Line.Jubilee]),
  [Station.CanonsPark]: new Set([Line.Jubilee]),
  [Station.Queensbury]: new Set([Line.Jubilee]),
  [Station.Kingsbury]: new Set([Line.Jubilee]),
  [Station.Neasden]: new Set([Line.Jubilee]),
  [Station.DollisHill]: new Set([Line.Jubilee]),
  [Station.WillesdenGreen]: new Set([Line.Jubilee]),
  [Station.Kilburn]: new Set([Line.Jubilee]),
  [Station.SwissCottage]: new Set([Line.Jubilee]),
  [Station.StJohnsWood]: new Set([Line.Jubilee]),
  [Station.NorthGreenwich]: new Set([Line.Jubilee]),
  [Station.Southwark]: new Set([Line.Jubilee]),

  [Station.Borough]: new Set([Line.Northern]),
  [Station.Edgware]: new Set([Line.Northern]),
  [Station.BurntOak]: new Set([Line.Northern]),
  [Station.Colindale]: new Set([Line.Northern]),
  [Station.Balham]: new Set([Line.Northern]),
  [Station.Morden]: new Set([Line.Northern]),
  [Station.SouthWimbledon]: new Set([Line.Northern]),
  [Station.ColliersWood]: new Set([Line.Northern]),
  [Station.TootingBroadway]: new Set([Line.Northern]),
  [Station.TootingBec]: new Set([Line.Northern]),
  [Station.ClaphamSouth]: new Set([Line.Northern]),
  [Station.ClaphamCommon]: new Set([Line.Northern]),
  [Station.Oval]: new Set([Line.Northern]),
  [Station.ClaphamNorth]: new Set([Line.Northern]),
  [Station.Kennington]: new Set([Line.Northern]),
  [Station.OldStreet]: new Set([Line.Northern]),
  [Station.BatterseaPowerStation]: new Set([Line.Northern]),
  [Station.NineElms]: new Set([Line.Northern]),
  [Station.Angel]: new Set([Line.Northern]),
  [Station.HighBarnet]: new Set([Line.Northern]),
  [Station.TotteridgeWhetstone]: new Set([Line.Northern]),
  [Station.WoodsidePark]: new Set([Line.Northern]),
  [Station.WestFinchley]: new Set([Line.Northern]),
  [Station.FinchleyCentral]: new Set([Line.Northern]),
  [Station.EastFinchley]: new Set([Line.Northern]),
  [Station.Highgate]: new Set([Line.Northern]),
  [Station.Archway]: new Set([Line.Northern]),
  [Station.KentishTown]: new Set([Line.Northern]),
  [Station.TufnellPark]: new Set([Line.Northern]),
  [Station.HendonCentral]: new Set([Line.Northern]),
  [Station.BrentCross]: new Set([Line.Northern]),
  [Station.GoldersGreen]: new Set([Line.Northern]),
  [Station.Hampstead]: new Set([Line.Northern]),
  [Station.BelsizePark]: new Set([Line.Northern]),
  [Station.ChalkFarm]: new Set([Line.Northern]),
  [Station.CamdenTown]: new Set([Line.Northern]),
  [Station.MorningtonCrescent]: new Set([Line.Northern]),
  [Station.GoodgeStreet]: new Set([Line.Northern]),
  [Station.MillHillEast]: new Set([Line.Northern]),

  [Station.CaledonianRoad]: new Set([Line.Piccadilly]),
  [Station.Knightsbridge]: new Set([Line.Piccadilly]),
  [Station.HydeParkCorner]: new Set([Line.Piccadilly]),
  [Station.CoventGarden]: new Set([Line.Piccadilly]),
  [Station.HollowayRoad]: new Set([Line.Piccadilly]),
  [Station.Arsenal]: new Set([Line.Piccadilly]),
  [Station.ManorHouse]: new Set([Line.Piccadilly]),
  [Station.TurnpikeLane]: new Set([Line.Piccadilly]),
  [Station.WoodGreen]: new Set([Line.Piccadilly]),
  [Station.BoundsGreen]: new Set([Line.Piccadilly]),
  [Station.ArnosGrove]: new Set([Line.Piccadilly]),
  [Station.Southgate]: new Set([Line.Piccadilly]),
  [Station.Cockfosters]: new Set([Line.Piccadilly]),
  [Station.Oakwood]: new Set([Line.Piccadilly]),
  [Station.RussellSquare]: new Set([Line.Piccadilly]),
  [Station.HattonCross]: new Set([Line.Piccadilly]),
  [Station.HounslowWest]: new Set([Line.Piccadilly]),
  [Station.HounslowEast]: new Set([Line.Piccadilly]),
  [Station.HounslowCentral]: new Set([Line.Piccadilly]),
  [Station.Osterley]: new Set([Line.Piccadilly]),
  [Station.SouthEaling]: new Set([Line.Piccadilly]),
  [Station.BostonManor]: new Set([Line.Piccadilly]),
  [Station.Northfields]: new Set([Line.Piccadilly]),
  [Station.NorthEaling]: new Set([Line.Piccadilly]),
  [Station.ParkRoyal]: new Set([Line.Piccadilly]),
  [Station.Alperton]: new Set([Line.Piccadilly]),
  [Station.SudburyTown]: new Set([Line.Piccadilly]),
  [Station.SudburyHill]: new Set([Line.Piccadilly]),
  [Station.SouthHarrow]: new Set([Line.Piccadilly]),
  [Station.NorthEaling]: new Set([Line.Piccadilly]),
  [Station.ParkRoyal]: new Set([Line.Piccadilly]),
  [Station.Alperton]: new Set([Line.Piccadilly]),

  [Station.TottenhamHale]: new Set([Line.Victoria]),
  [Station.Vauxhall]: new Set([Line.Victoria]),
  [Station.Pimlico]: new Set([Line.Victoria]),
  [Station.Brixton]: new Set([Line.Victoria]),

  [Station.Marylebone]: new Set([Line.Bakerloo]),
  [Station.LambethNorth]: new Set([Line.Bakerloo]),
  [Station.RegentsPark]: new Set([Line.Bakerloo]),
  [Station.MaidaVale]: new Set([Line.Bakerloo]),
  [Station.WarwickAvenue]: new Set([Line.Bakerloo]),
  [Station.KilburnPark]: new Set([Line.Bakerloo]),
  [Station.EdgwareRoadBakerloo]: new Set([Line.Bakerloo]),

  [Station.Leyton]: new Set([Line.Central]),
  [Station.Epping]: new Set([Line.Central]),
  [Station.Debden]: new Set([Line.Central]),
  [Station.Loughton]: new Set([Line.Central]),
  [Station.GantsHill]: new Set([Line.Central]),
  [Station.Redbridge]: new Set([Line.Central]),
  [Station.Leytonstone]: new Set([Line.Central]),
  [Station.TheydonBois]: new Set([Line.Central]),
  [Station.StPauls]: new Set([Line.Central]),
  [Station.LancasterGate]: new Set([Line.Central]),
  [Station.HollandPark]: new Set([Line.Central]),
  [Station.BuckhurstHill]: new Set([Line.Central]),
  [Station.Chigwell]: new Set([Line.Central]),
  [Station.GrangeHill]: new Set([Line.Central]),
  [Station.RodingValley]: new Set([Line.Central]),
  [Station.NewburyPark]: new Set([Line.Central]),
  [Station.Barkingside]: new Set([Line.Central]),
  [Station.Fairlop]: new Set([Line.Central]),
  [Station.Hainault]: new Set([Line.Central]),
  [Station.Snaresbrook]: new Set([Line.Central]),
  [Station.SouthWoodford]: new Set([Line.Central]),
  [Station.Woodford]: new Set([Line.Central]),
  [Station.Wanstead]: new Set([Line.Central]),
  [Station.ChanceryLane]: new Set([Line.Central]),
  [Station.BethnalGreenCentral]: new Set([Line.Central]),
  [Station.WhiteCity]: new Set([Line.Central]),
  [Station.EastCity]: new Set([Line.Central]),
  [Station.MarbleArch]: new Set([Line.Central]),
  [Station.Queensway]: new Set([Line.Central]),
  [Station.NorthActon]: new Set([Line.Central]),
  [Station.WestActon]: new Set([Line.Central]),
  [Station.WestRuislip]: new Set([Line.Central]),
  [Station.Northolt]: new Set([Line.Central]),
  [Station.Greenford]: new Set([Line.Central]),
  [Station.SouthRuislip]: new Set([Line.Central]),
  [Station.RuislipGardens]: new Set([Line.Central]),
  [Station.HangerLane]: new Set([Line.Central]),
  [Station.Perivale]: new Set([Line.Central]),

  [Station.Limehouse]: new Set([Line.DLR]),
  [Station.Westferry]: new Set([Line.DLR]),
  [Station.Poplar]: new Set([Line.DLR]),
  [Station.Blackwall]: new Set([Line.DLR]),
  [Station.StarLane]: new Set([Line.DLR]),
  [Station.AbbeyRoad]: new Set([Line.DLR]),
  [Station.StratfordHighStreet]: new Set([Line.DLR]),
  [Station.StratfordInternational]: new Set([Line.DLR]),
  [Station.TowerGateway]: new Set([Line.DLR]),
  [Station.CuttySarkForMaritimeGreenwich]: new Set([Line.DLR]),
  [Station.Greenwich]: new Set([Line.DLR]),
  [Station.Lewisham]: new Set([Line.DLR]),
  [Station.WoolwichArsenal]: new Set([Line.DLR]),
  [Station.LondonCityAirport]: new Set([Line.DLR]),
  [Station.EastIndia]: new Set([Line.DLR]),
  [Station.PuddingMillLane]: new Set([Line.DLR]),
  [Station.CanningTown]: new Set([Line.DLR]),
  [Station.WestIndiaQuay]: new Set([Line.DLR]),
  [Station.HeronQuays]: new Set([Line.DLR]),
  [Station.Mudchute]: new Set([Line.DLR]),
  [Station.Crossharbour]: new Set([Line.DLR]),
  [Station.SouthQuay]: new Set([Line.DLR]),
  [Station.DeptfordBridge]: new Set([Line.DLR]),
  [Station.IslandGardens]: new Set([Line.DLR]),
  [Station.BowChurch]: new Set([Line.DLR]),
  [Station.RoyalVictoria]: new Set([Line.DLR]),
  [Station.Beckton]: new Set([Line.DLR]),
  [Station.AllSaints]: new Set([Line.DLR]),
  [Station.LangdonPark]: new Set([Line.DLR]),
  [Station.DevonsRoad]: new Set([Line.DLR]),
  [Station.ElversonRoad]: new Set([Line.DLR]),
  [Station.GallionsReach]: new Set([Line.DLR]),
  [Station.Cyprus]: new Set([Line.DLR]),
  [Station.BecktonPark]: new Set([Line.DLR]),
  [Station.RoyalAlbert]: new Set([Line.DLR]),
  [Station.PrinceRegent]: new Set([Line.DLR]),
  [Station.KingGeorgeV]: new Set([Line.DLR]),
  [Station.PontoonDock]: new Set([Line.DLR]),
  [Station.WestSilvertown]: new Set([Line.DLR]),

  [Station.Upminster]: new Set([Line.District]),
  [Station.UpminsterBridge]: new Set([Line.District]),
  [Station.Hornchurch]: new Set([Line.District]),
  [Station.ElmPark]: new Set([Line.District]),
  [Station.DagenhamEast]: new Set([Line.District]),
  [Station.DagenhamHeathway]: new Set([Line.District]),
  [Station.Becontree]: new Set([Line.District]),
  [Station.Upney]: new Set([Line.District]),
  [Station.PutneyBridge]: new Set([Line.District]),
  [Station.WestKensington]: new Set([Line.District]),
  [Station.RavenscourtPark]: new Set([Line.District]),
  [Station.StamfordBrook]: new Set([Line.District]),
  [Station.WimbledonPark]: new Set([Line.District]),
  [Station.Southfields]: new Set([Line.District]),
  [Station.EastPutney]: new Set([Line.District]),
  [Station.ParsonsGreen]: new Set([Line.District]),
  [Station.FulhamBroadway]: new Set([Line.District]),

  [Station.Chesham]: new Set([Line.Metropolitan]),
  [Station.Amersham]: new Set([Line.Metropolitan]),
  [Station.ChalfontLatimer]: new Set([Line.Metropolitan]),
  [Station.Chorleywood]: new Set([Line.Metropolitan]),
  [Station.Watford]: new Set([Line.Metropolitan]),
  [Station.Rickmansworth]: new Set([Line.Metropolitan]),
  [Station.Croxley]: new Set([Line.Metropolitan]),
  [Station.MoorPark]: new Set([Line.Metropolitan]),
  [Station.Northwood]: new Set([Line.Metropolitan]),
  [Station.NorthwoodHills]: new Set([Line.Metropolitan]),
  [Station.Pinner]: new Set([Line.Metropolitan]),
  [Station.NorthHarrow]: new Set([Line.Metropolitan]),
  [Station.PrestonRoad]: new Set([Line.Metropolitan]),
  [Station.HarrowOnTheHill]: new Set([Line.Metropolitan]),
  [Station.WestHarrow]: new Set([Line.Metropolitan]),
  [Station.NorthwickPark]: new Set([Line.Metropolitan]),

  [Station.BeckenhamJunction]: new Set([Line.Tram]),
  [Station.BeckenhamRoad]: new Set([Line.Tram]),
  [Station.AvenueRoad]: new Set([Line.Tram]),
  [Station.Birkbeck]: new Set([Line.Tram]),
  [Station.HarringtonRoad]: new Set([Line.Tram]),
  [Station.ElmersEnd]: new Set([Line.Tram]),
  [Station.Arena]: new Set([Line.Tram]),
  [Station.Woodside]: new Set([Line.Tram]),
  [Station.BlackhorseLane]: new Set([Line.Tram]),
  [Station.Addiscombe]: new Set([Line.Tram]),
  [Station.Sandilands]: new Set([Line.Tram]),
  [Station.LloydPark]: new Set([Line.Tram]),
  [Station.CoombeLane]: new Set([Line.Tram]),
  [Station.GravelHill]: new Set([Line.Tram]),
  [Station.AddingtonVillage]: new Set([Line.Tram]),
  [Station.Fieldway]: new Set([Line.Tram]),
  [Station.KingHenrysDrive]: new Set([Line.Tram]),
  [Station.NewAddington]: new Set([Line.Tram]),
  [Station.LebanonRoad]: new Set([Line.Tram]),
  [Station.EastCroydon]: new Set([Line.Tram]),
  [Station.GeorgeStreet]: new Set([Line.Tram]),
  [Station.WellesleyRoad]: new Set([Line.Tram]),
  [Station.Centrale]: new Set([Line.Tram]),
  [Station.ChurchStreet]: new Set([Line.Tram]),
  [Station.ReevesCorner]: new Set([Line.Tram]),
  [Station.WandlePark]: new Set([Line.Tram]),
  [Station.WaddonMarsh]: new Set([Line.Tram]),
  [Station.AmpereWay]: new Set([Line.Tram]),
  [Station.TherapiaLane]: new Set([Line.Tram]),
  [Station.BeddingtonLane]: new Set([Line.Tram]),
  [Station.Mitcham]: new Set([Line.Tram]),
  [Station.MitchamJunction]: new Set([Line.Tram]),
  [Station.BelgraveWalk]: new Set([Line.Tram]),
  [Station.PhippsBridge]: new Set([Line.Tram]),
  [Station.MordenRoad]: new Set([Line.Tram]),
  [Station.MertonPark]: new Set([Line.Tram]),
  [Station.DundonaldRoad]: new Set([Line.Tram]),

  [Station.IFSCloudRoyalDocks]: new Set([Line.CloudCableCar]),
  [Station.IFSCloudGreenwichPeninsula]: new Set([Line.CloudCableCar]),

  [Station.HeathrowTerminals23]: new Set([Line.Piccadilly, Line.Elizabeth]),
  [Station.HeathrowTerminal5]: new Set([Line.Piccadilly, Line.Elizabeth]),
  [Station.HeathrowTerminal4]: new Set([Line.Piccadilly, Line.Elizabeth]),

  [Station.PiccadillyCircus]: new Set([Line.Bakerloo, Line.Piccadilly]),
  [Station.ElephantCastle]: new Set([Line.Northern, Line.Bakerloo]),
  [Station.CharingCross]: new Set([Line.Northern, Line.Bakerloo]),
  [Station.WembleyCentral]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.WillesdenJunction]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.Harlesden]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.StonebridgePark]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.QueensPark]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.KensalGreen]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.SouthKenton]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.Kenton]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.NorthWembley]: new Set([Line.Bakerloo, Line.Overground]),
  [Station.HarrowWealdstone]: new Set([Line.Overground, Line.Bakerloo]),

  [Station.UptonPark]: new Set([Line.District, Line.HammersmithCity]),
  [Station.EastHam]: new Set([Line.District, Line.HammersmithCity]),
  [Station.BromleyByBow]: new Set([Line.District, Line.HammersmithCity]),
  [Station.StepneyGreen]: new Set([Line.District, Line.HammersmithCity]),
  [Station.AldgateEast]: new Set([Line.District, Line.HammersmithCity]),
  [Station.Plaistow]: new Set([Line.District, Line.HammersmithCity]),
  [Station.BowRoad]: new Set([Line.District, Line.HammersmithCity]),

  [Station.WoodLane]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.WestbournePark]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.RoyalOak]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.LadbrokeGrove]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.LatimerRoad]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.GoldhawkRoad]: new Set([Line.Circle, Line.HammersmithCity]),
  [Station.ShepherdsBushMarket]: new Set([Line.Circle, Line.HammersmithCity]),

  [Station.Eastcote]: new Set([Line.Metropolitan, Line.Piccadilly]),
  [Station.RuislipManor]: new Set([Line.Metropolitan, Line.Piccadilly]),
  [Station.Ruislip]: new Set([Line.Metropolitan, Line.Piccadilly]),
  [Station.Hillingdon]: new Set([Line.Metropolitan, Line.Piccadilly]),
  [Station.Uxbridge]: new Set([Line.Metropolitan, Line.Piccadilly]),
  [Station.Ickenham]: new Set([Line.Metropolitan, Line.Piccadilly]),

  [Station.Romford]: new Set([Line.Elizabeth, Line.Overground]),
  [Station.ShepherdsBush]: new Set([Line.Central, Line.Overground]),
  [Station.ShepherdsBushOverground]: new Set([Line.Central, Line.Overground]),
  [Station.Wimbledon]: new Set([Line.District, Line.Tram]),
  [Station.EarlsCourt]: new Set([Line.Piccadilly, Line.District]),
  [Station.ChiswickPark]: new Set([Line.Piccadilly, Line.District]),
  [Station.TurnhamGreen]: new Set([Line.Piccadilly, Line.District]),
  [Station.BaronsCourt]: new Set([Line.Piccadilly, Line.District]),
  [Station.EalingCommon]: new Set([Line.Overground, Line.Piccadilly]),
  [Station.Gunnersbury]: new Set([Line.Overground, Line.District]),
  [Station.KewGardens]: new Set([Line.Overground, Line.District]),
  [Station.Richmond]: new Set([Line.Overground, Line.District]),
  [Station.WestBrompton]: new Set([Line.District, Line.Overground]),
  [Station.GreenPark]: new Set([Line.Piccadilly, Line.Jubilee, Line.Victoria]),
  [Station.CanadaWater]: new Set([Line.Overground, Line.Jubilee]),
  [Station.LondonBridge]: new Set([Line.Northern, Line.Jubilee]),
  [Station.WarrenStreet]: new Set([Line.Northern, Line.Victoria]),
  [Station.LeicesterSquare]: new Set([Line.Northern, Line.Piccadilly]),
  [Station.RaynersLane]: new Set([Line.Piccadilly, Line.Metropolitan]),
  [Station.FinsburyPark]: new Set([Line.Piccadilly, Line.Victoria]),
  [Station.BlackhorseRoad]: new Set([Line.Overground, Line.Victoria]),
  [Station.HighburyIslington]: new Set([Line.Overground, Line.Victoria]),
  [Station.SevenSisters]: new Set([Line.Overground, Line.Victoria]),
  [Station.WalthamstowCentral]: new Set([Line.Overground, Line.Victoria]),
  [Station.Stockwell]: new Set([Line.Northern, Line.Victoria]),
  [Station.CustomHouseForExCeL]: new Set([Line.DLR, Line.Elizabeth]),
  [Station.KensingtonOlympia]: new Set([Line.District, Line.Overground]),
  [Station.WestCroydon]: new Set([Line.Tram, Line.Overground]),
  [Station.WestCroydonTram]: new Set([Line.Tram, Line.Overground]),
  [Station.Shadwell]: new Set([Line.DLR, Line.Overground]),
  [Station.ShadwellDLR]: new Set([Line.DLR, Line.Overground]),
  [Station.ActonTown]: new Set([Line.District, Line.Piccadilly]),
  [Station.Bank]: new Set([Line.DLR, Line.Central, Line.Northern]),
  [Station.WembleyPark]: new Set([Line.Jubilee, Line.Metropolitan]),
  [Station.TowerHill]: new Set([Line.Circle, Line.District]),
  [Station.Monument]: new Set([Line.Circle, Line.District]),
  [Station.CannonStreet]: new Set([Line.Circle, Line.District]),
  [Station.MansionHouse]: new Set([Line.Circle, Line.District]),
  [Station.Blackfriars]: new Set([Line.Circle, Line.District]),
  [Station.Temple]: new Set([Line.Circle, Line.District]),
  [Station.StJamessPark]: new Set([Line.Circle, Line.District]),
  [Station.SloaneSquare]: new Set([Line.Circle, Line.District]),
  [Station.Bayswater]: new Set([Line.Circle, Line.District]),
  [Station.HighStreetKensington]: new Set([Line.Circle, Line.District]),
  [Station.Victoria]: new Set([Line.Circle, Line.District, Line.Victoria]),
  [Station.CanaryWharf]: new Set([Line.Elizabeth, Line.DLR, Line.Jubilee]),
  [Station.WestHampstead]: new Set([Line.Overground, Line.Jubilee]),
  [Station.WestHampsteadJubilee]: new Set([Line.Overground, Line.Jubilee]),
  [Station.FinchleyRoad]: new Set([Line.Jubilee, Line.Metropolitan]),
  [Station.Aldgate]: new Set([Line.Circle, Line.Metropolitan]),
  [Station.Holborn]: new Set([Line.Central, Line.Piccadilly]),
  [Station.BondStreet]: new Set([Line.Jubilee, Line.Elizabeth, Line.Central]),
  [Station.OxfordCircus]: new Set([Line.Central, Line.Bakerloo, Line.Victoria]),
  [Station.EdgwareRoad]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.District,
  ]),
  [Station.NottingHillGate]: new Set([
    Line.Circle,
    Line.District,
    Line.Central,
  ]),
  [Station.MileEnd]: new Set([
    Line.District,
    Line.HammersmithCity,
    Line.Central,
  ]),
  [Station.Barking]: new Set([
    Line.District,
    Line.HammersmithCity,
    Line.Overground,
  ]),
  [Station.Farringdon]: new Set([
    Line.Circle,
    Line.Elizabeth,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.KingsCrossStPancras]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
    Line.Northern,
    Line.Piccadilly,
    Line.Victoria,
  ]),
  [Station.Paddington]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.District,
    Line.Elizabeth,
    Line.HammersmithCity,
  ]),
  [Station.BakerStreet]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.HammersmithCity,
    Line.Jubilee,
    Line.Metropolitan,
  ]),
  [Station.Embankment]: new Set([
    Line.Bakerloo,
    Line.Circle,
    Line.District,
    Line.Northern,
  ]),
  [Station.Westminster]: new Set([Line.Circle, Line.District, Line.Jubilee]),
  [Station.SouthKensington]: new Set([
    Line.Circle,
    Line.District,
    Line.Piccadilly,
  ]),
  [Station.GloucesterRoad]: new Set([
    Line.Circle,
    Line.District,
    Line.Piccadilly,
  ]),
  [Station.Moorgate]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
    Line.Northern,
  ]),
  [Station.EustonSquare]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.Barbican]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.GreatPortlandStreet]: new Set([
    Line.Circle,
    Line.HammersmithCity,
    Line.Metropolitan,
  ]),
  [Station.EalingBroadway]: new Set([
    Line.District,
    Line.Elizabeth,
    Line.Central,
  ]),
  [Station.TottenhamCourtRoad]: new Set([
    Line.Northern,
    Line.Elizabeth,
    Line.Central,
  ]),
  [Station.Euston]: new Set([Line.Northern, Line.Overground, Line.Victoria]),
  [Station.LiverpoolStreet]: new Set([
    Line.Elizabeth,
    Line.Circle,
    Line.Central,
    Line.HammersmithCity,
    Line.Overground,
    Line.Metropolitan,
  ]),
  [Station.Waterloo]: new Set([
    Line.Jubilee,
    Line.Bakerloo,
    Line.Northern,
    Line.Waterloo,
  ]),
  [Station.Whitechapel]: new Set([
    Line.District,
    Line.Elizabeth,
    Line.HammersmithCity,
    Line.Overground,
  ]),
  [Station.WestHam]: new Set([
    Line.District,
    Line.HammersmithCity,
    Line.Jubilee,
    Line.DLR,
  ]),
  [Station.Hammersmith]: new Set([
    Line.Circle,
    Line.District,
    Line.HammersmithCity,
    Line.Piccadilly,
  ]),
  [Station.Stratford]: new Set([
    Line.Central,
    Line.DLR,
    Line.Elizabeth,
    Line.Jubilee,
    Line.Overground,
  ]),
};

// spread values for enum for single word stations
// needed for the search functionality later
export const multiWordStationNames: Partial<Record<Station, string>> = {
  [Station.StPauls]: "St Paul’s",
  [Station.KingsCrossStPancras]: "King’s Cross & St Pancras International",
  [Station.MansionHouse]: "Mansion House",
  [Station.CanonsPark]: "Canons Park",
  [Station.WillesdenGreen]: "Willesden Green",
  [Station.DollisHill]: "Dollis Hill",
  [Station.PrestonRoad]: "Preston Road",
  [Station.WembleyPark]: "Wembley Park",
  [Station.BakerStreet]: "Baker Street",
  [Station.GreatPortlandStreet]: "Great Portland Street",
  [Station.StJamessPark]: "St James's Park",
  [Station.GloucesterRoad]: "Gloucester Road",
  [Station.SloaneSquare]: "Sloane Square",
  [Station.HighStreetKensington]: "High Street Kensington",
  [Station.NottingHillGate]: "Notting Hill Gate",
  [Station.CannonStreet]: "Cannon Street",
  [Station.LiverpoolStreet]: "Liverpool Street",
  [Station.SouthKensington]: "South Kensington",
  [Station.CanaryWharf]: "Canary Wharf",
  [Station.PutneyBridge]: "Putney Bridge",
  [Station.HayesHarlington]: "Hayes & Harlington",
  [Station.WestEaling]: "West Ealing",
  [Station.ActonMainLine]: "Acton Main Line",
  [Station.CustomHouseForExCeL]: "Custom House for ExCeL",
  [Station.LambethNorth]: "Lambeth North",
  [Station.LancasterGate]: "Lancaster Gate",
  [Station.StJohnsWood]: "St John’s Wood",
  [Station.WestHampstead]: "West Hampstead",
  [Station.FinchleyRoad]: "Finchley Road",
  [Station.SwissCottage]: "Swiss Cottage",
  [Station.BeckenhamJunction]: "Beckenham Junction",
  [Station.LebanonRoad]: "Lebanon Road",
  [Station.EastCroydon]: "East Croydon",
  [Station.MitchamJunction]: "Mitcham Junction",
  [Station.GeorgeStreet]: "George Street",
  [Station.WaddonMarsh]: "Waddon Marsh",
  [Station.TherapiaLane]: "Therapia Lane",
  [Station.MordenRoad]: "Morden Road",
  [Station.BelgraveWalk]: "Belgrave Walk",
  [Station.PhippsBridge]: "Phipps Bridge",
  [Station.ChurchStreet]: "Church Street",
  [Station.PhippsBridge]: "Wandle Park",
  [Station.AmpereWay]: "Ampere Way",
  [Station.BeddingtonLane]: "Beddington Lane",
  [Station.ReevesCorner]: "Reeves Corner",
  [Station.WellesleyRoad]: "Wellesley Road",
  [Station.LloydPark]: "Lloyd Park",
  [Station.CoombeLane]: "Coombe Lane",
  [Station.GravelHill]: "Gravel Hill",
  [Station.AddingtonVillage]: "Addington Village",
  [Station.NewAddington]: "New Addington",
  [Station.KingHenrysDrive]: "King Henry’s Drive",
  [Station.MertonPark]: "Merton Park",
  [Station.BlackhorseLane]: "Blackhorse Lane",
  [Station.DundonaldRoad]: "Dundonald Road",
  [Station.HarringtonRoad]: "Harrington Road",
  [Station.CaledonianRoad]: "Caledonian Road",
  [Station.StPauls]: "St Paul's",
  [Station.ClaphamJunction]: "Clapham Junction",
  [Station.DalstonJunction]: "Dalston Junction",
  [Station.ShoreditchHighStreet]: "Shoreditch High Street",
  [Station.UpperHolloway]: "Upper Holloway",
  [Station.CrouchHill]: "Crouch Hill",
  [Station.SouthTottenham]: "South Tottenham",
  [Station.HarringayGreenLanes]: "Harringay Green Lanes",
  [Station.ActonTown]: "Acton Town",
  [Station.WoodgrangePark]: "Woodgrange Park",
  [Station.WalthamstowQueensRoad]: "Walthamstow Queen's Road",
  [Station.LeytonMidlandRoad]: "Leyton Midland Road",
  [Station.LeytonstoneHighRoad]: "Leytonstone High Road",
  [Station.WansteadPark]: "Wanstead Park",
  [Station.ImperialWharf]: "Imperial Wharf",
  [Station.WandsworthRoad]: "Wandsworth Road",
  [Station.DenmarkHill]: "Denmark Hill",
  [Station.PeckhamRye]: "Peckham Rye",
  [Station.QueensRoadPeckham]: "Queens Road Peckham",
  [Station.SurreyQuays]: "Surrey Quays",
  [Station.CrystalPalace]: "Crystal Palace",
  [Station.NewCross]: "New Cross",
  [Station.WestCroydon]: "West Croydon",
  [Station.HonorOakPark]: "Honor Oak Park",
  [Station.PengeWest]: "Penge West",
  [Station.ForestHill]: "Forest Hill",
  [Station.NorwoodJunction]: "Norwood Junction",
  [Station.HackneyWick]: "Hackney Wick",
  [Station.CaledonianRoadBarnsbury]: "Caledonian Road & Barnsbury",
  [Station.HackneyCentral]: "Hackney Central",
  [Station.DalstonKingsland]: "Dalston Kingsland",
  [Station.CamdenRoad]: "Camden Road",
  [Station.KentishTownWest]: "Kentish Town West",
  [Station.GospelOak]: "Gospel Oak",
  [Station.FinchleyRoadFrognal]: "Finchley Road & Frognal",
  [Station.HampsteadHeath]: "Hampstead Heath",
  [Station.BrondesburyPark]: "Brondesbury Park",
  [Station.KensalRise]: "Kensal Rise",
  [Station.SouthHampstead]: "South Hampstead",
  [Station.KilburnHighRoad]: "Kilburn High Road",
  [Station.KensingtonOlympia]: "Kensington (Olympia)",
  [Station.SouthActon]: "South Acton",
  [Station.ActonCentral]: "Acton Central",
  [Station.StarLane]: "Star Lane",
  [Station.AbbeyRoad]: "Abbey Road",
  [Station.StratfordHighStreet]: "Stratford High Street",
  [Station.TowerHill]: "Tower Hill",
  [Station.StratfordInternational]: "Stratford International",
  [Station.TowerGateway]: "Tower Gateway",
  [Station.CuttySarkForMaritimeGreenwich]: "Cutty Sark for Maritime Greenwich",
  [Station.AbbeyWood]: "Abbey Wood",
  [Station.WoolwichArsenal]: "Woolwich Arsenal",
  [Station.LondonCityAirport]: "London City Airport",
  [Station.EastIndia]: "East India",
  [Station.PuddingMillLane]: "Pudding Mill Lane",
  [Station.CanningTown]: "Canning Town",
  [Station.AllSaints]: "All Saints",
  [Station.LangdonPark]: "Langdon Park",
  [Station.DevonsRoad]: "Devons Road",
  [Station.ElversonRoad]: "Elverson Road",
  [Station.WestIndiaQuay]: "West India Quay",
  [Station.SouthQuay]: "South Quay",
  [Station.HeronQuays]: "Heron Quays",
  [Station.DeptfordBridge]: "Deptford Bridge",
  [Station.IslandGardens]: "Island Gardens",
  [Station.BowChurch]: "Bow Church",
  [Station.RoyalVictoria]: "Royal Victoria",
  [Station.GallionsReach]: "Gallions Reach",
  [Station.BecktonPark]: "Beckton Park",
  [Station.RoyalAlbert]: "Royal Albert",
  [Station.PrinceRegent]: "Prince Regent",
  [Station.KingGeorgeV]: "King George V",
  [Station.PontoonDock]: "Pontoon Dock",
  [Station.WestSilvertown]: "West Silvertown",
  [Station.WalthamstowCentral]: "Walthamstow Central",
  [Station.SevenSisters]: "Seven Sisters",
  [Station.FinsburyPark]: "Finsbury Park",
  [Station.HighburyIslington]: "Highbury & Islington",
  [Station.BlackhorseRoad]: "Blackhorse Road",
  [Station.HollowayRoad]: "Holloway Road",
  [Station.ManorHouse]: "Manor House",
  [Station.TurnpikeLane]: "Turnpike Lane",
  [Station.WoodGreen]: "Wood Green",
  [Station.BoundsGreen]: "Bounds Green",
  [Station.ArnosGrove]: "Arnos Grove",
  [Station.CoventGarden]: "Covent Garden",
  [Station.HydeParkCorner]: "Hyde Park Corner",
  [Station.RussellSquare]: "Russell Square",
  [Station.HeathrowTerminals23]: "Heathrow Terminals 2 & 3",
  [Station.HattonCross]: "Hatton Cross",
  [Station.HounslowWest]: "Hounslow West",
  [Station.HounslowEast]: "Hounslow East",
  [Station.HounslowCentral]: "Hounslow Central",
  [Station.HeathrowTerminal5]: "Heathrow Terminal 5",
  [Station.HeathrowTerminal4]: "Heathrow Terminal 4",
  [Station.SouthEaling]: "South Ealing",
  [Station.BostonManor]: "Boston Manor",
  [Station.NorthEaling]: "North Ealing",
  [Station.ParkRoyal]: "Park Royal",
  [Station.SudburyTown]: "Sudbury Town",
  [Station.SudburyHill]: "Sudbury Hill",
  [Station.SouthHarrow]: "South Harrow",
  [Station.RaynersLane]: "Rayners Lane",
  [Station.SouthWimbledon]: "South Wimbledon",
  [Station.ColliersWood]: "Colliers Wood",
  [Station.TootingBroadway]: "Tooting Broadway",
  [Station.TootingBec]: "Tooting Bec",
  [Station.ClaphamSouth]: "Clapham South",
  [Station.ClaphamCommon]: "Clapham Common",
  [Station.ClaphamHighStreet]: "Clapham High Street",
  [Station.ClaphamNorth]: "Clapham North",
  [Station.BurntOak]: "Burnt Oak",
  [Station.TotteridgeWhetstone]: "Totteridge & Whetstone",
  [Station.BatterseaPowerStation]: "Battersea Power Station",
  [Station.NineElms]: "Nine Elms",
  [Station.LeicesterSquare]: "Leicester Square",
  [Station.WarrenStreet]: "Warren Street",
  [Station.GoodgeStreet]: "Goodge Street",
  [Station.MorningtonCrescent]: "Mornington Crescent",
  [Station.CamdenTown]: "Camden Town",
  [Station.ChalkFarm]: "Chalk Farm",
  [Station.BelsizePark]: "Belsize Park",
  [Station.GoldersGreen]: "Golders Green",
  [Station.BrentCross]: "Brent Cross",
  [Station.HendonCentral]: "Hendon Central",
  [Station.TufnellPark]: "Tufnell Park",
  [Station.KentishTown]: "Kentish Town",
  [Station.EastFinchley]: "East Finchley",
  [Station.FinchleyCentral]: "Finchley Central",
  [Station.WestFinchley]: "West Finchley",
  [Station.WoodsidePark]: "Woodside Park",
  [Station.HighBarnet]: "High Barnet",
  [Station.MillHillEast]: "Mill Hill East",
  [Station.NorthEaling]: "North Ealing",
  [Station.NorthGreenwich]: "North Greenwich",
  [Station.LondonBridge]: "London Bridge",
  [Station.GreenPark]: "Green Park",
  [Station.CanadaWater]: "Canada Water",
  [Station.IFSCloudRoyalDocks]: "IFS Cloud Royal Docks",
  [Station.IFSCloudGreenwichPeninsula]: "IFS Cloud Greenwich Peninsula",
  [Station.KewGardens]: "Kew Gardens",
  [Station.BaronsCourt]: "Barons Court",
  [Station.EalingCommon]: "Ealing Common",
  [Station.WestKensington]: "West Kensington",
  [Station.RavenscourtPark]: "Ravenscourt Park",
  [Station.StamfordBrook]: "Stamford Brook",
  [Station.TurnhamGreen]: "Turnham Green",
  [Station.ChiswickPark]: "Chiswick Park",
  [Station.EarlsCourt]: "Earl's Court",
  [Station.TheydonBois]: "Theydon Bois",
  [Station.BuckhurstHill]: "Buckhurst Hill",
  [Station.ShepherdsBushMarket]: "Shepherd’s Bush Market",
  [Station.WestBrompton]: "West Brompton",
  [Station.EastPutney]: "East Putney",
  [Station.ParsonsGreen]: "Parsons Green",
  [Station.FulhamBroadway]: "Fulham Broadway",
  [Station.BarkingRiverside]: "Barking Riverside",
  [Station.UptonPark]: "Upton Park",
  [Station.EastHam]: "East Ham",
  [Station.BromleyByBow]: "Bromley-by-Bow",
  [Station.StepneyGreen]: "Stepney Green",
  [Station.AldgateEast]: "Aldgate East",
  [Station.WestHam]: "West Ham",
  [Station.BowRoad]: "Bow Road",
  [Station.WestbournePark]: "Westbourne Park",
  [Station.RoyalOak]: "Royal Oak",
  [Station.LadbrokeGrove]: "Ladbroke Grove",
  [Station.LatimerRoad]: "Latimer Road",
  [Station.GoldhawkRoad]: "Goldhawk Road",
  [Station.BuckhurstHill]: "Buckhurst Hill",
  [Station.UpminsterBridge]: "Upminster Bridge",
  [Station.ElmPark]: "Elm Park",
  [Station.DagenhamEast]: "Dagenham East",
  [Station.DagenhamHeathway]: "Dagenham Heathway",
  [Station.WimbledonPark]: "Wimbledon Park",
  [Station.WoodLane]: "Wood Lane",
  [Station.GantsHill]: "Gants Hill",
  [Station.GrangeHill]: "Grange Hill",
  [Station.RodingValley]: "Roding Valley",
  [Station.NewburyPark]: "Newbury Park",
  [Station.SouthWoodford]: "South Woodford",
  [Station.ChanceryLane]: "Chancery Lane",
  [Station.MileEnd]: "Mile End",
  [Station.BethnalGreenCentral]: "Bethnal Green",
  [Station.BethnalGreenOverground]: "Bethnal Green",
  [Station.TottenhamCourtRoad]: "Tottenham Court Road",
  [Station.ShepherdsBush]: "Shepherd's Bush",
  [Station.RegentsPark]: "Regent’s Park",
  [Station.ElephantCastle]: "Elephant & Castle",
  [Station.WhiteCity]: "White City",
  [Station.EastCity]: "East City",
  [Station.MarbleArch]: "Marble Arch",
  [Station.NorthActon]: "North Acton",
  [Station.BondStreet]: "Bond Street",
  [Station.WestActon]: "West Acton",
  [Station.EalingBroadway]: "Ealing Broadway",
  [Station.WestRuislip]: "West Ruislip",
  [Station.SouthRuislip]: "South Ruislip",
  [Station.RuislipGardens]: "Ruislip Gardens",
  [Station.HangerLane]: "Hanger Lane",
  [Station.CharingCross]: "Charing Cross",
  [Station.PiccadillyCircus]: "Piccadilly Circus",
  [Station.OxfordCircus]: "Oxford Circus",
  [Station.EdgwareRoadBakerloo]: "Edgware Road",
  [Station.EdgwareRoad]: "Edgware Road",
  [Station.MaidaVale]: "Maida Vale",
  [Station.WarwickAvenue]: "Warwick Avenue",
  [Station.KilburnPark]: "Kilburn Park",
  [Station.WembleyCentral]: "Wembley Central",
  [Station.WillesdenJunction]: "Willesden Junction",
  [Station.StonebridgePark]: "Stonebridge Park",
  [Station.QueensPark]: "Queen’s Park",
  [Station.KensalGreen]: "Kensal Green",
  [Station.SouthKenton]: "South Kenton",
  [Station.NorthWembley]: "North Wembley",
  [Station.WatfordJunction]: "Watford Junction",
  [Station.HeadstoneLane]: "Headstone Lane",
  [Station.HatchEnd]: "Hatch End",
  [Station.CarpendersPark]: "Carpenders Park",
  [Station.WatfordHighStreet]: "Watford High Street",
  [Station.HarrowWealdstone]: "Harrow & Wealdstone",
  [Station.HarrowOnTheHill]: "Harrow-on-the-Hill",
  [Station.WestHarrow]: "West Harrow",
  [Station.NorthwickPark]: "Northwick Park",
  [Station.RuislipManor]: "Ruislip Manor",
  [Station.NorthHarrow]: "North Harrow",
  [Station.NorthwoodHills]: "Northwood Hills",
  [Station.MoorPark]: "Moor Park",
  [Station.ChalfontLatimer]: "Chalfont & Latimer",
  [Station.ElmersEnd]: "Elmers End",
  [Station.WoodStreet]: "Wood Street",
  [Station.ForestGate]: "Forest Gate",
  [Station.ManorPark]: "Manor Park",
  [Station.EmersonPark]: "Emerson Park",
  [Station.SevenKings]: "Seven Kings",
  [Station.HaroldWood]: "Harold Wood",
  [Station.GideaPark]: "Gidea Park",
  [Station.ChadwellHeath]: "Chadwell Heath",
  [Station.EdmontonGreen]: "Edmonton Green",
  [Station.HackneyDowns]: "Hackney Downs",
  [Station.StokeNewington]: "Stoke Newington",
  [Station.StJamesStreet]: "St James Street",
  [Station.BushHillPark]: "Bush Hill Park",
  [Station.EnfieldTown]: "Enfield Town",
  [Station.TheobaldsGrove]: "Theobalds Grove",
  [Station.WatfordJunction]: "Watford Junction",
  [Station.TurkeyStreet]: "Turkey Street",
  [Station.SilverStreet]: "Silver Street",
  [Station.WhiteHartLane]: "White Hart Lane",
  [Station.BruceGrove]: "Bruce Grove",
  [Station.RectoryRoad]: "Rectory Road",
  [Station.LondonFields]: "London Fields",
  [Station.CambridgeHeath]: "Cambridge Heath",
  [Station.HighamsPark]: "Highams Park",
  [Station.TottenhamHale]: "Tottenham Hale",
};

export const multiWordLineNames: Partial<Record<Line, string>> = {
  [Line.HammersmithCity]: "Hammersmith & City",
  [Line.Waterloo]: "Waterloo & City",
  [Line.Elizabeth]: "Elizabeth line",
  [Line.CloudCableCar]: "IFS Cloud Cable Car",
};
